### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ajith-reddy-dev** [meanbee/slack-jira-bot#11]
2020/06/03 09:50:31 Exception responding to issue TEST-124: runtime error: invalid memory address or nil pointer dereference
2020/06/03 09:50:54 main: Current latency: 1.110534ms
2020/06/03 09:51:24 main: Current latency: 1.093479ms
2020/06/03 09:51:54 main: Current latency: 1.13508ms
2020/06/03 09:52:13 handleMessage: Identified IOS-7290 in message

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
