### ISSUE TITLE
%s invalid character '\x1f' looking for beginning of value

### ISSUE THREAD

**Issue by noahlz** [meanbee/slack-jira-bot#6]
We installed this slack bot over a year ago (Feb 2016) and it has been an awesome part of our workflow.  But this week we had to restart the VM that hosted the docker container running it, and it stopped working.

Once we got it up and running again, we find it errors on every single message as follows:

```
2017/05/03 19:27:25 handleMessage: Identified AN-2146 in message
%s invalid character '\x1f' looking for beginning of value
2017/05/03 19:27:26 Exception responding to issue AN-2146: runtime error: invalid memory address or nil pointer dereference
```

**Comment by punkstar** [comment]
Weird.  I've not got strong golang experience but I'd like to try and reproduce.  Are you using the docker image?  Do you have any version numbers for your environment, etc?

**Comment by noahlz** [comment]
We are using the docker image.

[slack-jira-bot.inspect.txt](https://github.com/meanbee/slack-jira-bot/files/974671/slack-jira-bot.inspect.txt)

BTW how can we get back the image we installed in Feb 2016? On Docker Hub it just has "3 months ago"

https://hub.docker.com/r/meanbee/slack-jira-bot/tags/

**Comment by noahlz** [comment]
Our docker version:

```
$ docker --version
Docker version 1.10.1, build 9e83765
```

**Comment by punkstar** [comment]
@noahlz Can you give the `go-1.8` tag a go in your environment?  I did some work on it last night to update deps and the golang runtime.  I've not merged it into master yet as I need to fix the travis build.

I was only able to reproduce your error when I was missing some environment variables.  Can you confirm you've got the correct variables defined for your running container?

**Comment by noahlz** [comment]
Hmm... here's the command we use to start the container. Actual secrets removed of course:

`docker run -it --restart=always -d -e JIRA_BASEURL=https://issues.novus.com -e JIRA_USERNAME='user' -e JIRA_PASSWORD='<secret>' -e SLACK_API_KEY=<secret> quay.io/meanbee/slack-jira-bot:latest`

**Comment by noahlz** [comment]
~~I think some debugging / logging output, and perhaps having an error occur when required environment variables are missing, would be helpful.~~

EDIT: I see that's there: jira-bot.go#L206

I guess some error logging providing more details on the URL accessed and the response? Anyway, we'll look at using a new go version, and/or wait for the new build.

**Comment by noahlz** [comment]
with `go-1.8` tag

```
2017/05/04 22:37:48 handleMessage: Identified SUPPORT-3135 in message
%s invalid character '\x1f' looking for beginning of value
2017/05/04 22:37:48 issueData: {    <nil> 0001-01-01 00:00:00 +0000 UTC}
2017/05/04 22:37:48 Exception responding to issue SUPPORT-3135: runtime error: invalid memory address or nil pointer dereference
2017/05/04 22:38:05 main: Current latency: 34.536243ms
```

**Comment by punkstar** [comment]
@noahlz I've pushed a new build to the `latest` tag that has some more error checking around missing assignees on issues however your problem appears to be that the issue data simply isn't being returned from Jira correctly.  You can see on the `issueData` line you posted above, the data that we're getting back is blank.

A couple of things to debug further:

* Can you confirm your Jira credentials are correct?
* Do you see the full issue details when you visit https://issues.novus.com/rest/api/2/issue/SUPPORT-3135? I think just being logged into your Jira account through the browser and visiting will be enough to authenticate.

Feel free to pull down `latest` from https://hub.docker.com/r/meanbee/slack-jira-bot (I'm going to stop publishing to quay) and see how that goes, but I don't think it will help.

**Comment by noahlz** [comment]
jira bot is back for us. Thank you!

```
Unable to find image 'meanbee/slack-jira-bot:latest' locally
latest: Pulling from meanbee/slack-jira-bot
cd0a524342ef: Already exists 
e39c3ffe4133: Already exists 
85334a7c2001: Already exists 
b5844b8ce46a: Already exists 
07530c4e04c3: Already exists 
b0679b0a872e: Already exists 
3b3241e48946: Already exists 
c94bf41679f4: Pull complete 
74f60236e141: Pull complete 
Digest: sha256:0074d6002547a9565e6b72bcc58d8bf0d50b49e2dac163178bdbf043ee95eb6b
Status: Downloaded newer image for meanbee/slack-jira-bot:latest
7313d2bc0e104a0a7b5f0667f3277032c1928bc094e07d1f60c5dc3e6e34a366
```

After pulling latest from docker hub (instead of quay.io) and confirming the user / password as correct, it's live again.  Thanks for your help!

BTW I also wrote a JIRA API tool (for reporting on bug fix KPIs) which I got clearance to open source earlier this year. I'll hit you up when it's online.

Thanks!

- @noahlz

**Comment by punkstar** [comment]
@noahlz Great news. I wish I knew what actually caused the problem though! Look forward to seeing the tool.

**Comment by shift** [comment]
This issue has just cropped up for us today, no changes since we deployed the bot via the latest docker image about a week ago.

```
2017/08/23 15:42:55 handleMessage: Identified TD-2 in message
%s invalid character '<' looking for beginning of value
2017/08/23 15:42:55 issueData: {    <nil> 0001-01-01 00:00:00 +0000 UTC}
2017/08/23 15:42:55 Exception responding to issue TD-2: runtime error: invalid memory address or nil pointer dereference
```

**Comment by punkstar** [comment]
![](https://media.giphy.com/media/l0HlDHQEiIdY3kxlm/giphy.gif)

@shift Can you trying the debugging steps I mentioned on https://github.com/meanbee/slack-jira-bot/issues/6#issuecomment-299435787?

**Comment by shift** [comment]
It seems this was due to JIRA putting up a CAPTCHA. So I changed the password of the bot user, which threw an error the same, then updated the container to use the new password and everything worked again.

**Comment by punkstar** [comment]
@shift Where was it prompting for a CAPTCHA?  When you tried to log in as the bot user?

@noahlz If you're still using this image, have you run into this issue again?

**Comment by shift** [comment]
@punkstar Yeah JIRA was requesting the user to login requiring a CAPTCHA which was throwing an error. Seems something else using the same account had an invalid password and triggered the CAPTCHA requirement.

**Comment by noahlz** [comment]
We don't have this problem since we started using 

`"Image": "sha256:383b6eb7f5914bcd756dfd9eb1c31dd60abad5abbcb9c5f58252accf33d75b2f"`

It's been running for 3 months without incident.

**Comment by noahlz** [comment]
I'm back over a year later! We restarted our vms and that triggered a re-login. Yes, this error seems to be because it needs a captcha

![image](https://user-images.githubusercontent.com/447754/47741562-f292c700-dc50-11e8-8f25-73e9593f9ffb.png)

PS we are JIRA server so we can't use the new Slack/Atlassian JIRA Cloud solution.

**Comment by noahlz** [comment]
Also the problem was that my password was wrong and then my account got locked out :man_shrugging: 

I think this is good to close.

**Comment by noahlz** [comment]
Message from the mysterious future.... This issue happened again, and the user is not locked out, nor has CAPTCHA. sigh....

```
2020/03/17 16:29:06 handleMessage: Identified AN-13332 in message
%s invalid character '<' looking for beginning of value
2020/03/17 16:29:26 issueData: {    <nil> 0001-01-01 00:00:00 +0000 UTC}
2020/03/17 16:29:26 Exception responding to issue AN-13332: runtime error: invalid memory address or nil pointer dereference

```

**Comment by noahlz** [comment]
j/c I got it working again by copy-pasting this command and adding my login details:

```
docker run -it --restart=always -d \
    -e JIRA_BASEURL=https://yourjirainstall.atlassian.net \
    -e JIRA_USERNAME='yourjirausername' \
    -e JIRA_PASSWORD='yourjirapassword' \
    -e SLACK_API_KEY='yourslackapikey' \
    meanbee/slack-jira-bot:latest
```

No idea what i did differently, but if anybody else is having this problem (me in the future perhaps) that's how I resolved it.
